train:
  batch_size: 32 
  epochs: 10
  eval_interval: 1
  learning_rate: 0.0001
  eval_iters: 100
  max_batches_per_epoch: 3000
model:
  dim_context: 128 
  dim_embedding: 192
  dim_feedforward: 768
  num_heads: 3
  num_layers: 3
  prob_dropout: 0.2